spring:
  datasource:
    url: jdbc:mysql://192.168.31.189:3306/StrayFootball?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Sunalong@123
    driver-class-name: com.mysql.jdbc.Driver
  #redis
  redis:
    host: 192.168.31.189
    password: "@zmkjemubao888999"
    port: 6869
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8